### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [gambardellawill/cezshanne#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by gambardellawill** [comment]
@unixorn Done. Ship it! :shipit:
Mind you that this project is *literally* 2 days old. Since I'm building this as my daily driver theme for `zsh`, there'll sure be a lot of updates to it.
